



CREATE TABLE IF NOT EXISTS FACT_ANIME (
    ANIME_SK_ID INT AUTOINCREMENT PRIMARY KEY,
    ANIME_ID INT NOT NULL UNIQUE,
    STUDIO_ID INT,
    TITLE VARCHAR(99) NOT NULL,
    DURATION INT NOT NULL,
    EPISODES INT NOT NULL,
    SCORE DECIMAL(2,1) NOT NULL,
    AIRED_FROM DATE NOT NULL,
    AIRED_TO DATE,
    IS_CURRENT BOOLEAN NOT NULL,
    VALIDATED BOOLEAN NOT NULL,
    TIMESTAMP_LOADED DATE NOT NULL,
    FOREIGN KEY (STUDIO_ID) REFERENCES DIM_STUDIO(STUDIO_ID)
);