

CREATE TABLE IF NOT EXISTS BRIDGE_ANIME_GENRE (
    ANIME_ID INT,
    GENRE_ID INT,
    PRIMARY KEY (ANIME_ID, GENRE_ID),
    FOREIGN KEY (ANIME_ID) REFERENCES FACT_ANIME(ANIME_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES DIM_GENRE(GENRE_ID)
);
