


name: Unittests

on:
    push:
        branches:
            - dev

jobs:

  unittests:
    runs-on: ubuntu-24.04
    env:
        PYTHONPATH: .

    steps:
        - uses: actions/checkout@v4

        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            architecture: 'x64'

        - name: install requirements
          run: pip install -r requirements.txt

        - name: unittests
          run: |
            cd ./application/tests
            pytest -v -s

  validate-infrastructure-configurations:
    needs:  unittests
    runs-on: ubuntu-24.04
  
    defaults:
        run:
          working-directory: infrastructure
  
    steps:
        - name: clone GitHub repo to ubuntu machine
          uses: actions/checkout@v4
  
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{secrets.DEVELOPER_ACCESS_KEY}}
            aws-secret-access-key: ${{secrets.DEVELOPER_SECRET_ACCESS_KEY}}
            aws-region: ${{secrets.INFRASTRCUTURE_REGION}}
  
        - name: setup terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.9.5
  
        - name: initialize terraform
          run: |
            export TFSTATE_BUCKET=${{secrets.TFSTATE_TRACKER_BUCKET}}
            export TFSTATE_REGION=${{secrets.INFRASTRCUTURE_REGION}}
            
            terraform init \
              -backend-config="bucket=$TFSTATE_BUCKET" \
              -backend-config="key=infra-2/terraform.tfstate" \
              -backend-config="region=$TFSTATE_REGION" \
              -backend-config="encrypt=true"
  
        - name: validate infra config syntax
          run: terraform validate
  
        - name: plan and check changes
          run: |
            echo '${{secrets.SNOWFLAKE_DB_CREDENTIALS}}' > db_creds.json
  
            terraform plan \
                -var="pipeline_region=${{secrets.INFRASTRCUTURE_REGION}}" \
                -var="data_lake=${{secrets.ANIME_DATA_LAKE_BUCKET}}" \
                -var="secrets_manager_db_credentials=$(cat db_creds.json)" \
                -var="account_id=${{secrets.ACCOUNT_ID}}" \
                -var="secrets_manager_path=${{secrets.SECRETS_MANAGER_PATH}}"
          