


name: Unittests

on:
    push:
        branches:
            - dev

jobs:

  unittests:
    runs-on: ubuntu-24.04

    steps:
        - uses: actions/checkout@v4

        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            architecture: 'x64'

        - name: install requirements
          run: pip install -r requirements.txt

        - name: set python path
          run: PYTHONPATH=. 

        - name: unittests
          run: |
            cd ./application/tests
            pytest -v -s